[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 50
via-ir = true
block_number = 1
# 101 gwei 
gas_price = 101000000000
block_timestamp = 100

[profile.default.optimizer_details]
inliner = true
jumpdest_remover = true
order_literals = true
deduplicate = true
cse = true
constant_optimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
