[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 10_000_000
via-ir = true
block_number = 1
# 101 gwei 
gas_price = 101000000000
block_timestamp = 1600000000

[profile.default.optimizer_details]
inliner = true
jumpdest_remover = true
order_literals = true
deduplicate = true
cse = true
constant_optimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

[profile.noopt]
src = 'contracts'
out = 'out'
libs = ['lib']
optimizer = false
via-ir = true
block_number = 1
# 101 gwei 
gas_price = 101000000000
block_timestamp = 1600000000

[profile.noopt.optimizer_details.yulDetails]
optimizerSteps = ''

