[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 500
via-ir = true
block_number = 1
# 101 gwei this configuration is required for tests to have a tx.gasprice
gas_price = 101000000000

[profile.default.optimizer_details]
inliner = true
jumpdest_remover = true
order_literals = true
deduplicate = true
cse = true
constant_optimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true