name: test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'

env:
  FOUNDRY_PROFILE: ci
  ALCHEMY_DEVNET_RPC: ${{ secrets.ALCHEMY_DEVNET_RPC }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: collective-governance-v1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name:  Deploy Goerly Testnet
        run: |
          forge create ElectorVoterPool --contracts contracts/ElectorVoterPool.sol --rpc-url ${ALCHEMY_DEVNET_RPC}