name: Sepolia Testnet

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [created]

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: collective-governance-v1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Yarn install
        run: |
          yarn install --dev
          yarn prettier:check
          yarn hint
          yarn install --production

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Deploy Constant Library
        run: |
          forge create --json --contracts contracts/Constant.sol --rpc-url ${RPC_URL} --private-key ${PRIVATE_KEY} Constant | tee Constant.sol.json
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}

      - name: Deploy to Sepolia Testnet
        run: |
          export DEPLOYED_LIBRARY=$(bin/library.py Constant.sol.json)
          echo "Using library ${DEPLOYED_LIBRARY}"
          forge script ./script/DeployCollective.sol --sig 'deploy()' --libraries ${DEPLOYED_LIBRARY} --slow --broadcast --rpc-url ${RPC_URL} --private-key ${PRIVATE_KEY} --etherscan-api-key ${ETHERSCAN_API_KEY} --verify
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
