name: Sepolia Testnet

on:
  push:
    tags:
      - "*"

concurrency:
  group: "ghcr-image"
  cancel-in-progress: true

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  COMMUNIITY_BUILDER_ADDRESS: "0xa36e161361A16D75534d565480e62cE474BaC9f3"
  GOVERNANCE_BUILDER_ADDRESS: "0x9fB5a925E61c31617129B5D030808939DADA99f7"
  TREASURY_BUILDER_ADDRESS: "0x49753b58270ae454d4ec555ff88294a4fab01660"
  ECDSA_LIB_ADDRESS: "0xe9e21aaEaEad9c57C1F4c622915fFB54f9Ebe338"
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: collective-governance-v1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Yarn install
        run: |
          yarn install --dev
          yarn prettier:check
          yarn hint
          yarn install --production

      - name: Run Forge tests
        run: |
          forge test -v --fail-fast
        id: test

      - name: GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body_path: CHANGELOG.md

      - name: Deploy Constant Library
        run: |
          forge create --json --contracts contracts/Constant.sol --rpc-url ${RPC_URL} --private-key ${PRIVATE_KEY} Constant | tee Constant.sol.json

      - name: Deploy Community Builder to Testnet
        run: |
          export DEPLOYED_LIBRARY=$(bin/library.py Constant.sol.json)
          echo "Using library ${DEPLOYED_LIBRARY}"
          forge script ./script/DeployCommunityBuilder.sol --sig 'upgrade()' --libraries ${DEPLOYED_LIBRARY} --slow --broadcast --rpc-url ${RPC_URL} --private-key ${PRIVATE_KEY}
        env:
          BUILDER_ADDRESS: ${COMMUNITY_BUILDER_ADDRESS}

      - name: Deploy Collective Governance to Testnet
        run: |
          export DEPLOYED_LIBRARY=$(bin/library.py Constant.sol.json)
          echo "Using library ${DEPLOYED_LIBRARY}"
          forge script ./script/DeployCollective.sol --sig 'upgrade()' --libraries ${DEPLOYED_LIBRARY} --slow --broadcast --rpc-url ${RPC_URL} --private-key ${PRIVATE_KEY}
        env:
          BUILDER_ADDRESS: ${GOVERNANCE_BUILDER_ADDRESS}

      - name: Deploy Treasury Builder to Testnet
        run: |
          export DEPLOYED_LIBRARY=$(bin/library.py Constant.sol.json)
          echo "Using library ${DEPLOYED_LIBRARY}"
          forge script ./script/DeployTreasuryBuilder.sol --sig 'upgrade()' --libraries ./lib/openzeppelin-contracts/contracts/utils/cryptography/ECDSA.sol:ECDSA:${ECDSA_LIB_ADDRESS} --libraries ${DEPLOYED_LIBRARY} --slow --broadcast --rpc-url ${RPC_URL} --private-key ${PRIVATE_KEY}
        env:
          BUILDER_ADDRESS: ${TREASURY_BUILDER_ADDRESS}
