name: Goerli Testnet

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types: [created]

env:
  FOUNDRY_PROFILE: ci
  DEVNET_RPC: ${{ secrets.ALCHEMY_DEVNET_RPC }}
  DEVNET_WALLET: ${{ secrets.GOERLI_WALLET }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: collective-governance-v1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Yarn install
        run: |
          yarn install --dev
          yarn lint
          yarn install --production

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Deploy Goerli Testnet
        run: |
          forge create --contracts contracts/CollectiveGovernance.sol --rpc-url ${DEVNET_RPC} --private-key ${DEVNET_WALLET} --etherscan-api-key ${ETHERSCAN_API_KEY} --verify CollectiveGovernance
          forge inspect contracts/CollectiveGovernance.sol:CollectiveGovernance abi
        if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
